# Generated by Django 6.0.5 on 2026-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=3),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
